### ISSUE TITLE
Clicking "Expand Protein Complexes" has no effect

### ISSUE THREAD

**Issue by pkalita-lbl** [geneontology/wc-gocam-viz#61]
Currently, in the latest version in `main`, clicking on the "Expand Protein Complexes" button has no effect (other than changing the button label to "Collapse Protein Complexes"). It looks like this was working as of version `1.0.1`, but broke sometime after that. 

Looking at GO-CAM `6606056e00002011`, I would expect that clicking "Expand Protein Complexes" would change the label of the "B cell receptor complex" node to "CD79B, CD79A".

**Comment by pkalita-lbl** [comment]
There is an error in the browser console when clicking the button:

```
gocam-viz.tsx:395 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at GoCamViz.createComplex (gocam-viz.tsx:395:31)
    at gocam-viz.tsx:324:31
    at Array.forEach (<anonymous>)
    at GoCamViz.renderGoCam (gocam-viz.tsx:318:24)
    at GoCamViz.toggleComplex (gocam-viz.tsx:569:14)
    at HTMLButtonElement.onClick (gocam-viz.tsx:754:57)
```

**Comment by tmushayahama** [comment]
@pkalita-lbl thanks for catching this bug, I had totally forgotten that the new data model, there is no longer an id by GO root type i.e. BP, CC, MF, PCC, etc bcz back then it was hardcoded as there was only one of each. So this is line was giving the error

``` js
 const edges = activity.getEdges(ActivityNodeType.GoProteinContainingComplex)
```

So maybe for now a hack is to traverse from MF, we gatta have a proper data model later

**Comment by vanaukenk** [comment]
@tmushayahama 
Testing this fix on noctua-dev, the expand and collapse functionality is working, but the lable presented in the expanded protein complex box is not correct.  In this example it's saying there are two more members, but there aren't; there are only the five listed:

![Image](https://github.com/user-attachments/assets/fadc4467-efa8-474c-94fa-cad783b9f7ed)

http://noctua-dev.berkeleybop.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A67299f1a00000071

**Comment by vanaukenk** [comment]
The expand protein complexes functionality now displays the first three members when expanded and if there are more members, clicking on the complex highlights the appropriate entry in the right-hand table.

I anticipate that we will be revisiting this issue wrt the default number of protein complex members displayed, but we will go with this for now.
